import { jsPDF } from "jspdf";
import type { Round } from "@shared/schema";

export interface PDFConfig {
  tournamentName: string;
  playersCount: number;
  courtsCount: number;
  rounds: Round[];
}

export function generateTournamentPDF({ tournamentName, playersCount, courtsCount, rounds }: PDFConfig): jsPDF {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.width;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 20;
  let yPosition = margin;

  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text(tournamentName, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Americano Format Tournament Schedule', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 8;
  pdf.setFontSize(10);
  pdf.text(`${playersCount} Players • ${courtsCount} Courts`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 5;
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });

  // Draw header underline
  yPosition += 8;
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Rounds
  rounds.forEach((round, roundIndex) => {
    // Check if we need a new page
    const estimatedRoundHeight = 8 + (round.matches.length * 25);
    if (yPosition + estimatedRoundHeight > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }

    // Round header
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Round ${round.round}`, margin, yPosition);
    yPosition += 12;

    // Matches
    round.matches.forEach((match, matchIndex) => {
      // Check if we need a new page for this match
      if (yPosition + 25 > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }

      // Match box
      const boxHeight = 20;
      const boxWidth = pageWidth - (2 * margin);
      
      // Draw match box
      pdf.setDrawColor(200, 200, 200);
      pdf.setFillColor(248, 249, 250);
      pdf.rect(margin, yPosition, boxWidth, boxHeight, 'FD');

      // Court and game info
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Court ${match.court}`, margin + 5, yPosition + 6);
      pdf.text(`Game ${match.gameNumber}`, pageWidth - margin - 20, yPosition + 6);

      // Teams
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(0, 0, 0);
      
      const team1Text = `${match.team1[0]} & ${match.team1[1]}`;
      const team2Text = `${match.team2[0]} & ${match.team2[1]}`;
      
      pdf.text(team1Text, margin + 5, yPosition + 12);
      pdf.text('VS', pageWidth / 2 - 5, yPosition + 12);
      pdf.text(team2Text, margin + 5, yPosition + 17);

      yPosition += boxHeight + 5;
    });

    yPosition += 10;
  });

  // Tournament statistics
  if (yPosition + 40 > pageHeight - margin) {
    pdf.addPage();
    yPosition = margin;
  }

  yPosition += 10;
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Tournament Summary', margin, yPosition);
  yPosition += 12;

  const totalGames = rounds.reduce((sum, round) => sum + round.matches.length, 0);
  const gamesPerPlayer = Math.floor(totalGames * 4 / playersCount);
  const estimatedMinutes = totalGames * 30 + (rounds.length - 1) * 10; // 30 min per game + 10 min breaks

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`• Total Rounds: ${rounds.length}`, margin, yPosition);
  yPosition += 6;
  pdf.text(`• Total Games: ${totalGames}`, margin, yPosition);
  yPosition += 6;
  pdf.text(`• Games per Player: ~${gamesPerPlayer}`, margin, yPosition);
  yPosition += 6;
  pdf.text(`• Estimated Duration: ${Math.floor(estimatedMinutes / 60)}h ${estimatedMinutes % 60}m`, margin, yPosition);

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by Padel Tournament Scheduler', pageWidth / 2, pageHeight - 10, { align: 'center' });

  return pdf;
}

export function generatePDFPreviewHTML({ tournamentName, playersCount, courtsCount, rounds }: PDFConfig): string {
  const totalGames = rounds.reduce((sum, round) => sum + round.matches.length, 0);
  const gamesPerPlayer = Math.floor(totalGames * 4 / playersCount);
  const estimatedMinutes = totalGames * 30 + (rounds.length - 1) * 10;

  return `
    <div style="font-family: 'Inter', sans-serif; background: white; color: black; line-height: 1.5;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #000;">
        <h1 style="font-size: 24px; font-weight: bold; margin: 0; color: #000;">${tournamentName}</h1>
        <p style="font-size: 14px; color: #666; margin: 5px 0;">Americano Format Tournament Schedule</p>
        <p style="font-size: 12px; color: #666; margin: 5px 0;">${playersCount} Players • ${courtsCount} Courts</p>
        <p style="font-size: 10px; color: #666; margin: 5px 0;">Generated on ${new Date().toLocaleDateString()}</p>
      </div>

      <!-- Rounds -->
      ${rounds.map(round => `
        <div style="margin-bottom: 25px;">
          <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 15px; color: #000; border-bottom: 1px solid #ccc; padding-bottom: 5px;">
            Round ${round.round}
          </h2>
          <div style="display: grid; gap: 15px;">
            ${round.matches.map(match => `
              <div style="border: 1px solid #ddd; border-radius: 8px; padding: 15px; background: #f9f9f9;">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
                  <span style="font-weight: 600; color: #000;">Court ${match.court}</span>
                  <span style="font-size: 12px; color: #666;">Game ${match.gameNumber}</span>
                </div>
                <div style="display: flex; align-items: center; justify-content: space-between;">
                  <div style="text-align: center; flex: 1;">
                    <div style="font-weight: 500; color: #000; margin-bottom: 2px;">${match.team1[0]}</div>
                    <div style="font-weight: 500; color: #000; margin-bottom: 5px;">${match.team1[1]}</div>
                    <div style="font-size: 10px; color: #666;">Team 1</div>
                  </div>
                  <div style="font-size: 16px; font-weight: bold; color: #ccc; margin: 0 20px;">VS</div>
                  <div style="text-align: center; flex: 1;">
                    <div style="font-weight: 500; color: #000; margin-bottom: 2px;">${match.team2[0]}</div>
                    <div style="font-weight: 500; color: #000; margin-bottom: 5px;">${match.team2[1]}</div>
                    <div style="font-size: 10px; color: #666;">Team 2</div>
                  </div>
                </div>
              </div>
            `).join('')}
          </div>
        </div>
      `).join('')}

      <!-- Tournament Summary -->
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc;">
        <h3 style="font-size: 16px; font-weight: 600; margin-bottom: 15px; color: #000;">Tournament Summary</h3>
        <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px;">
          <div>
            <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Total Rounds</div>
            <div style="font-size: 18px; font-weight: bold; color: #000;">${rounds.length}</div>
          </div>
          <div>
            <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Total Games</div>
            <div style="font-size: 18px; font-weight: bold; color: #000;">${totalGames}</div>
          </div>
          <div>
            <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Games per Player</div>
            <div style="font-size: 18px; font-weight: bold; color: #000;">~${gamesPerPlayer}</div>
          </div>
          <div>
            <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Est. Duration</div>
            <div style="font-size: 18px; font-weight: bold; color: #000;">${Math.floor(estimatedMinutes / 60)}h ${estimatedMinutes % 60}m</div>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div style="margin-top: 40px; text-align: center;">
        <p style="font-size: 8px; color: #999; margin: 0;">Generated by Padel Tournament Scheduler</p>
      </div>
    </div>
  `;
}
